### ISSUE TITLE
Suggestions / questions

### ISSUE THREAD

**Issue by vatterspun** [Jay-Rad/CleanShot#2]
Hey a few quick things on this one:

* What formats does the program output to?  Animated GIF?  If it supports formats like MP4, does it record audio?
* what format does the screen capture tool output to?  
* Could you add a link to the home page to make it clear where visitors can download the release?
* What site does it upload to?

Essentially I recommend detailing this in on the github readme / home page.

**Comment by bitbound** [comment]
Thanks for the suggestion.  I added those to the readme.

Recap:

Captures are saved in PNG or GIF format. Uploads for sharing are sent to a web service at my site (https://lucency.co), and they are automatically deleted after 2 weeks.

Download current release: https://lucency.co/?app=CleanShot
